### ISSUE TITLE
using keccak256 hash function 

### ISSUE THREAD

**Issue by egeaybars123** [smartcontractkit/functions-hardhat-starter-kit#110]
In the documentation, it says that developers can require built-in crypto module. Does this crypto module refer to the encryptSecrets script in the sandbox folder? If not, does this module include keccak256 hash function? If it does, how can we import this hash function?

**Comment by KuphJr** [comment]
The `crypto` module refers to the build-in [Node.js crypto module](https://nodejs.org/api/crypto.html).

We do not yet provide a native keccak256 function in the initial version of the beta.  For now, you can copy-paste an implementation keccak256 hashing function into your JavaScript code.
