### ISSUE TITLE
Some responses are too big to be stored in `latestResponse`

### ISSUE THREAD

**Issue by Crypt0Hackers** [smartcontractkit/functions-hardhat-starter-kit#111]
Some API responses & function computations are larger than 32 bytes so the entire response can't be saved in `latestResponse`. Most notably ChatGPT due to the way it generates tokens (which I assume a lot of people will be trying out). 

In those cases it will throw this error: `Error message returned to client contract: "returned Buffer >256 bytes"`

**Comment by KuphJr** [comment]
Thanks for the feedback!
Currently, the maximum allowed response size is set at 256 bytes during the closed beta.
However, existing limits may change as this product continues to be developed.
