### ISSUE TITLE
No Concise Docs With Contract Examples

### ISSUE THREAD

**Issue by woodydeck** [smartcontractkit/functions-hardhat-starter-kit#112]
It is not clear what a basic implementation of a deployed contract looks like in the docs. The current docs require using Hardhat to setup. This goes against the standard in complementary documentation for subscriptions and VRF, things that will be frequently used with this service.

While Hardhat has its advantages in testing, having different styles of documentation makes it harder for developers to understand the macro picture of the underlying workings. It would be very nice to see a folder with compiled examples at the very least!

**Comment by KuphJr** [comment]
Thank you for the feedback!

As this product is still in beta, we do not yet have the full suite of tooling that is available for other products.  Stay tuned for updates as we continue to expand our documentation and tooling support.

**Comment by woodydeck** [comment]
Cheers. It's more of anti-tooling I would love to see! 

I believe strongly that Web3 should not use frameworks for mission critical things, at least not as a default. It is extremely important to understand at lower level each piece of the functionality because dapps must be built bulletproof from day 1. It's the opposite of the MVP and iterate approach of most development. You need to start with the finished roadmap with all externalities documenting from the beginning, and then test in order. While it is still iteration, you're starting from the goal and working back to the foundation.

When you abstract complex operations, you can mask potential issues.
