### ISSUE TITLE
Chainlink Functions is currently in a closed testing phase. 

### ISSUE THREAD

**Issue by mrhouzlane** [smartcontractkit/functions-hardhat-starter-kit#153]
Problem : 
```

Chainlink Functions is currently in a closed testing phase.
For access sign up here:
https://functions.chain.link
```

I'm following step by step : https://docs.chain.link/chainlink-functions/getting-started

How to get subscription with ID ?

**Comment by KuphJr** [comment]
Just complete the form at https://functions.chain.link to be added to the allowlist to create subscriptions! We update the allowlist every 24-48 hours.
