### ISSUE TITLE
Need encode multiple value

### ISSUE THREAD

**Issue by rooot044** [smartcontractkit/functions-hardhat-starter-kit#183]
We need implement this function

FunctionsModule.encode(["uint256", "string", "int256"], [1, "test", -1]);

Because many production app needs multiple value response.  it able to decode multiple value like this

function fulfillRequest(bytes32 requestId, bytes memory response, bytes memory err) internal override {
    abi.decode(response, (uint256, string, int256));
}

**Comment by KuphJr** [comment]
@rooot044 Thanks for the feature suggestion! I am going to close this issue, but know that your suggestion has been recorded internally.
