### ISSUE TITLE
functions-sub-add not working on Goerli

### ISSUE THREAD

**Issue by CL-Victor** [smartcontractkit/functions-hardhat-starter-kit#32]
Trying to add a newly deployed contract to an existing billing subid account the same wallet (deployer) owns.
I assume that this function has been disabled by default and the .ignore file has to be updated

Error:
Found & ignored ./build/artifacts ; is listed in .gitignore
Found & ignored ./build/cache ; is listed in .gitignore

**Comment by zeuslawyer** [comment]
hi @CL-Victor 

I wasn't able to reproduce this issue on Goerli.

I was able to 
1) `functions-deploy-client --network goerli` and create contract `FunctionsConsumer` at `0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D`

2) `npx hardhat functions-sub-create --network goerli --amount 0.00`  to create Sub Id 22

3) `functions-sub-add --network goerli  --subid 22 --contract 0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D` to create add my consumer contract to the list of authorised consumers.
```
Added consumer contract address 0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D to subscription 22
1 authorized consumer contract for subscription 22:
[ '0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D' ]
✨  Done in 32.97s.
```


This is what you were trying to achieve right?  Your error seems to relate to the hardhat build process and not so much the addition of a consumer contract to your subscription?

**Comment by CL-Victor** [comment]
Hi @zeuslawyer 
What if I previously deployed a first contract with subId 9 and would like to have a second contract under the same Billing registry account to centralise billing/funding management under 1 subId only. 

Taking your example:
1. Create a new contract `functions-deploy-client --network goerli` and create contract `FunctionsConsumer` at `0x12---example---12D` 
2. `functions-sub-add --network goerli  --subid 22 --contract 0x12---example---12D` to add the new contract to the same Billing/Funding account

**Comment by zeuslawyer** [comment]
hi @CL-Victor  I must be misunderstanding you because what I think you're describing is what I've done?

The contract doesnt have a subID.  its the other way around a Subscription has an ID and can have more than 1 approved consumers.

Adding a newly deployed consumer contract to a pre-existing subscription is done with `functions-sub-add`.


Isnt that the scenario you're talking about?

**Comment by CL-Victor** [comment]
So if you create another contract, and try to run the below command, you will successfully have both `0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D` and `newcontractaddress` under the Sub22?
`functions-sub-add --network goerli  --subid 22 --contract newcontractaddress`

With the expected log being 
```
Added consumer contract address newcontractaddress to subscription 22
1 authorized consumer contract for subscription 22:
[ '0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D','newcontractaddress' ]
```

**Comment by zeuslawyer** [comment]
@CL-Victor 

Yes. 


1. For `yhh functions-sub-add --network goerli  --subid 22 --contract 0xc43e990e4CF07E13C3530E31e9A45C98c882635A` I get:


```
Added consumer contract address 0xc43e990e4CF07E13C3530E31e9A45C98c882635A to subscription 22
2 authorized consumer contracts for subscription 22:
[
  '0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D',
  '0xc43e990e4CF07E13C3530E31e9A45C98c882635A'
]
✨  Done in 36.32s.
```

2.  For `yhh functions-sub-info --network goerli --subid 22`
```
Subscription 22 owner: 0x208AA722Aca42399eaC5192EE778e4D42f4E5De3
Balance: 0.0 LINK
2 authorized consumer contracts:
[
  '0x48CEC5A8e31d1ECeF2A89Eac52D9103243B7887D',
  '0xc43e990e4CF07E13C3530E31e9A45C98c882635A'
]
✨  Done in 2.84s.
```

Have you tried it? Are you getting an error?

**Comment by CL-Victor** [comment]
Yes this is exactly the process I was doing which failed on my side. 
I will try again and let you know. 

Thanks!
