### ISSUE TITLE
Error logs: Error encountered when calling fulfillRequest

### ISSUE THREAD

**Issue by CL-Victor** [smartcontractkit/functions-hardhat-starter-kit#50]
My `npx hardhat functions-simulate` is failing due to the length of the response. If I remove ",Twitch Contrulla" from the below decoded string, the fulfillRequest function is successful. Is it something we should make even more obvious in the console logs for devs to understand whether it comes from gaslimit or response bytes limitation? @KuphJr 

`__Output from sandboxed source code__
Output represented as a hex string: 0x53686173746120372c547769746368204a764d616669612c5477697463682057696c6c727a2c50575220776f727468756b2c54776974636820436f6e7472756c6c61
Decoded as a string: Shasta 7,Twitch JvMafia,Twitch Willrz,PWR worthuk,Twitch Contrulla

Error encountered when calling fulfillRequest in client contract.
Ensure the fulfillRequest function in the client contract is correct and the --gaslimit is sufficent.

Estimated transmission cost: 0.083559307848617261 LINK (This will vary based on gas price)
Base fee: 0.0 LINK
Total estimated cost: 0.083559307848617261 LINK`

**Comment by bolekk** [comment]
cc @KuphJr let's try to make that message explicit. I'd be also for raising the limit (1024?) since it's already been reported as problematic by several users.

**Comment by KuphJr** [comment]
Upon investigation, it became apparent that this error should have been caught by the simulator prior to the request erroring when it was initiated on-chain.  This should be resolved in the latest version of the external adapter which is now live.  @CL-Victor Can you reattempt the same request and report back?
