### ISSUE TITLE
Need to wait X blocks before verifying

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/functions-hardhat-starter-kit#72]
If you verify before polygonscan/etherscan has a chance to process the transaction, you'll run into an error where it can't verify the code.

[These lines](https://github.com/smartcontractkit/functions-hardhat-starter-kit/blob/c42721e7299095e26df15c431ddbad28e12469d5/tasks/Functions-client/deploy.js#L34) need to have a `wait` command for 3 number of blocks (I've found 6 to be pretty good. 4 is probably fine too. 2 is too low. )

**Comment by KuphJr** [comment]
This has been fixed.  The tooling will now wait a minimum of 6 blocks before attempting verification.
